permissions needed for waf logging
https://docs.aws.amazon.com/waf/latest/developerguide/logging-s3.html#logging-s3-permissions

Tested by removing the SCP from the root organisation and running TF. After detaching the policy the plan succeeds.

With the SCP attached you see:

AccessDeniedException: You don't have the permissions that are required to perform this operation. status code: 400